# Generated by Django 3.2.11 on 2022-02-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile_pics/thor_f.jpg', upload_to='profile_pics'),
        ),
    ]
