# Generated by Django 3.1.4 on 2022-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20220404_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=10),
        ),
    ]
